### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by wbotelhos** [marcelobarreto/via_cep#115]
Hi, @marcelobarreto ! 

Could you release a new version with [this PR](https://github.com/marcelobarreto/via_cep/pull/114).

Thanks!

**Comment by marcelobarreto** [comment]
[v3.1.4](https://github.com/marcelobarreto/via_cep/releases/tag/v3.1.4)

**Comment by marcelobarreto** [comment]
[v3.1.4](https://github.com/marcelobarreto/via_cep/releases/tag/v3.1.4)
